### ISSUE TITLE
TDM410p

### ISSUE THREAD

**Issue by jlnhab** [asterisk/dahdi-linux#43]
Hi,
Is there a support for the tdm410?
`Dec 20 17:22:31 ns sh[25951]: DAHDI_CHANCONFIG failed on channel 1: Invalid argument (22)
Dec 20 17:22:31 ns sh[25951]: Selected signaling not supported
Dec 20 17:22:31 ns sh[25951]: Possible causes:
Dec 20 17:22:31 ns sh[25951]: #011FXS signaling is being used on a FXS interface (use a FXO signaling variant)
Dec 20 17:22:31 ns sh[25951]: #011RBS signaling is being used on a E1 CCS span
Dec 20 17:22:31 ns sh[25951]: #011Signaling is being assigned to channel 16 of an E1 CAS span
Dec 20 17:22:31 ns systemd[1]: dahdi.service: Main process exited, code=exited, status=1/FAILURE
Dec 20 17:22:31 ns systemd[1]: dahdi.service: Failed with result 'exit-code'.
Dec 20 17:22:31 ns kernel: dahdi_ioctl_chanconfig: No channel for number 1
Dec 20 17:22:31 ns systemd[1]: Failed to start dahdi.service - The DAHDI drivers allow you to use your linux computer to accept incoming data and voice interfaces.`

Thanks for your help.

**Comment by InterLinked1** [comment]
> Hi, Is there a support for the tdm410? `Dec 20 17:22:31 ns sh[25951]: DAHDI_CHANCONFIG failed on channel 1: Invalid argument (22) Dec 20 17:22:31 ns sh[25951]: Selected signaling not supported Dec 20 17:22:31 ns sh[25951]: Possible causes: Dec 20 17:22:31 ns sh[25951]: #011FXS signaling is being used on a FXS interface (use a FXO signaling variant) Dec 20 17:22:31 ns sh[25951]: #011RBS signaling is being used on a E1 CCS span Dec 20 17:22:31 ns sh[25951]: #011Signaling is being assigned to channel 16 of an E1 CAS span Dec 20 17:22:31 ns systemd[1]: dahdi.service: Main process exited, code=exited, status=1/FAILURE Dec 20 17:22:31 ns systemd[1]: dahdi.service: Failed with result 'exit-code'. Dec 20 17:22:31 ns kernel: dahdi_ioctl_chanconfig: No channel for number 1 Dec 20 17:22:31 ns systemd[1]: Failed to start dahdi.service - The DAHDI drivers allow you to use your linux computer to accept incoming data and voice interfaces.`
> 
> Thanks for your help.

Not officially right now, but you can restore all the old drivers if you install using PhreakScript: https://github.com/InterLinked1/phreakscript

Make sure to use the `--drivers` option like so: `phreaknet install --dahdi --drivers`

**Comment by jlnhab** [comment]
It isn't working!
What diff speaks about enabling old cards please?

**Comment by InterLinked1** [comment]
> It isn't working! What diff speaks about enabling old cards please?

It's the `--drivers` option.
