### ISSUE TITLE
Debian 10 (Buster) - dahdi-linux 3.4.0 - Compile - error: missing binary operator before token "("

### ISSUE THREAD

**Issue by jared-bloomer** [asterisk/dahdi-linux#51]
OS: Debian 10 (Buster)
Kernel: 5.10.0-0.deb10.29-amd64
dahdi-linux release: 3.4.0

Issue:
I downloaded  a fresh copy of of dahdi-linux-3.4.0.tar.gz. I extracted it, and cd into the directory. I then ran `make` and it failed with the following error

```
/root/dahdi-linux-3.4.0/drivers/dahdi/xpp/xbus-sysfs.c:424:43: error: missing binary operator before token "("
  RHEL_RELEASE_CODE >= RHEL_RELEASE_VERSION(9,4)
```

**Comment by InterLinked1** [comment]
> OS: Debian 10 (Buster) Kernel: 5.10.0-0.deb10.29-amd64 dahdi-linux release: 3.4.0
> 
> Issue: I downloaded a fresh copy of of dahdi-linux-3.4.0.tar.gz. I extracted it, and cd into the directory. I then ran `make` and it failed with the following error
> 
> ```
> /root/dahdi-linux-3.4.0/drivers/dahdi/xpp/xbus-sysfs.c:424:43: error: missing binary operator before token "("
>   RHEL_RELEASE_CODE >= RHEL_RELEASE_VERSION(9,4)
> ```

The new maintainer introduced a regression for this when trying to resolve the issue for RHEL systems. Here is a patch that resolves the issue and should allow you to build: https://github.com/asterisk/dahdi-linux/pull/58

If you install using PhreakScript[1], it also has this (and other) fixes that may be needed.

[1] https://github.com/InterLinked1/phreakscript
